{
 "title": "Palo Alto Traffic",
 "tags": [
  "snmp",
  "telegraf",
  "RemoteAccess"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "PaloFirewall",
    "query": "SHOW TAG VALUES FROM \"system\" WITH KEY = \"hostname\""
   }
  ]
 },
 "panels": [
  {
   "title": "$PaloFirewall Active VPN Tunnels",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       {
        "params": [
         "panGPGWUtilizationActiveTunnels"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Active Tunnels" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$PaloFirewall$/" }
     ]
    }
   ]
  },
  {
   "title": "$PaloFirewall Active VPN Tunnels",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       {
        "params": [
         "panGPGWUtilizationActiveTunnels"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Active Tunnels" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$PaloFirewall$/" }
     ]
    }
   ]
  },
  {
   "title": "$PaloFirewall VPN Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "panGPGWUtilizationPct" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Utilization" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$PaloFirewall$/" }
     ]
    }
   ]
  },
  {
   "title": "$PaloFirewall All Interfaces In/Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bps", "label": "<- Out |  In ->" }
   ],
   "targets": [
    {
     "alias": "$tag_ifName $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "rawSql": "SELECT\n  $__timeEpoch(<time_column>),\n  <value column> as value,\n  <series name column> as metric\nFROM\n  <table name>\nWHERE\n  $__timeFilter(time_column)\nORDER BY\n  <time_column> ASC",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$PaloFirewall$/" }
     ]
    }
   ]
  },
  {
   "title": "$PaloFirewall GlobalProtect Interface In/Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bps", "label": "<- Out |  In ->" }
   ],
   "targets": [
    {
     "alias": "$tag_ifName $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "rawSql": "SELECT\n  $__timeEpoch(<time_column>),\n  <value column> as value,\n  <series name column> as metric\nFROM\n  <table name>\nWHERE\n  $__timeFilter(time_column)\nORDER BY\n  <time_column> ASC",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$PaloFirewall$/" },
      { "condition": "AND", "key": "ifName", "operator": "=", "value": "ae1.3" }
     ]
    }
   ]
  },
  {
   "title": "$PaloFirewall CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "panProcessorLoadSys" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "System" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$PaloFirewall$/" }
     ]
    }
   ]
  },
  {
   "title": "$PaloFirewall CPU Utilization (Sys)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "panProcessorLoadSys" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "System" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$PaloFirewall$/" }
     ]
    }
   ]
  },
  {
   "title": "$PaloFirewall CPU Utilization (Mgmt)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "panProcessorLoadMgmt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Management" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$PaloFirewall$/" }
     ]
    }
   ]
  },
  {
   "title": "$PaloFirewall All Interface List",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "snmp",
     "rawSql": "SELECT 1",
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$PaloFirewall$/" }
     ]
    }
   ]
  }
 ]
}