{
 "title": "System Center Operations Manager",
 "tags": [
  "MSSQL",
  "SCOM"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Agent Monitored Servers and Clusters",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT count(*) as Windows\r\n\r\n  FROM [OperationsManager].[dbo].[MTV_Computer]"
    }
   ]
  },
  {
   "title": "Ping & SNMP Monitored Devices",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT count(*) as Nodes\r\nFROM [OperationsManager].[dbo].[MTV_System$NetworkManagement$Node]"
    }
   ]
  },
  {
   "title": "Agent Monitored Linux Servers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT count(*) as Unix\r\n\r\n  FROM [OperationsManager].[dbo].[MTV_Microsoft$Unix$Computer]"
    }
   ]
  },
  {
   "title": "Alerts: Severe",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT count(*) as Severe\r\n  FROM [OperationsManager].[dbo].[AlertView]\r\n  WHere [TimeResolved] is null and Severity = 0"
    }
   ]
  },
  {
   "title": "Alerts: Warning",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT count(*) as Warning\r\n  FROM [OperationsManager].[dbo].[AlertView]\r\n  WHere [TimeResolved] is null and Severity = 1"
    }
   ]
  },
  {
   "title": "Alerts: Information",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT count(*) as Info\r\n  FROM [OperationsManager].[dbo].[AlertView]\r\n  WHere [TimeResolved] is null and Severity = 2"
    }
   ]
  },
  {
   "title": "Total Assets Monitored",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT count(*) as metric\r\n  FROM [lansweeperdb].[scorch].[SCOM]\r\n  "
    }
   ]
  },
  {
   "title": "SQL Log Backup Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeEpoch([TimeRaised]),\n  count(*) as value\n  \nFROM\n  [OperationsManager].[dbo].[AlertView]\nWHERE\n  $__timeFilter([TimeRaised]) and [AlertStringName] like 'MSSQL on Windows: Log Backup Failed to Complete' and [ResolutionState] = 0\n  Group By [AlertStringName], [TimeRaised]\nORDER BY\n  TimeRaised DESC"
    }
   ]
  },
  {
   "title": "SQL Log Full",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeEpoch([TimeRaised]),\n  count(*) as value\n  \nFROM\n  [OperationsManager].[dbo].[AlertView]\nWHERE\n  $__timeFilter([TimeRaised]) and [AlertStringName] like 'MSSQL on Windows: Database log file is full. Back up the transaction log for the database to free up some log space' and [ResolutionState] = 0\n  Group By [AlertStringName], [TimeRaised]\nORDER BY\n  TimeRaised DESC"
    }
   ]
  },
  {
   "title": "Computer Unreachable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeEpoch([TimeRaised]),\n  count(*) as value\n  \nFROM\n  [OperationsManager].[dbo].[AlertView]\nWHERE\n  $__timeFilter([TimeRaised]) and [AlertStringName] like 'Failed to Connect to Computer' and [ResolutionState] = 0\n  Group By [AlertStringName], [TimeRaised]\nORDER BY\n  TimeRaised DESC"
    }
   ]
  },
  {
   "title": "Network Device Unreachable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeEpoch([TimeRaised]),\n  count(*) as value\n  \nFROM\n  [OperationsManager].[dbo].[AlertView]\nWHERE\n  $__timeFilter([TimeRaised]) and [AlertStringName] like 'Network Device is Not Responding' and [ResolutionState] = 0\n  Group By [AlertStringName], [TimeRaised]\nORDER BY\n  TimeRaised DESC"
    }
   ]
  },
  {
   "title": "Low Disk Space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeEpoch([TimeRaised]),\n  count(*) as value\n  \nFROM\n  [OperationsManager].[dbo].[AlertView]\nWHERE\n  $__timeFilter([TimeRaised]) and [AlertStringName] like 'Logical Disk Free Space is low' and [ResolutionState] = 0\n  Group By [AlertStringName], [TimeRaised]\nORDER BY\n  TimeRaised DESC"
    }
   ]
  },
  {
   "title": "Servers in Maintenance Mode",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/****** Script for SelectTopNRows command from SSMS  ******/\r\nSELECT count([IsInMaintenanceMode])\r\n  FROM [OperationsManager].[dbo].[MaintenanceMode] as MM\r\n  inner join [OperationsManager].[dbo].[MTV_Microsoft$Windows$OperatingSystem] on [OperationsManager].[dbo].[MTV_Microsoft$Windows$OperatingSystem].BaseManagedEntityId = MM.[BaseManagedEntityId]\r\n  where [IsInMaintenanceMode] = 1"
    }
   ]
  },
  {
   "title": "OpsMgr Sample Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Performance Counter Query",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": " SELECT   \r\n vPerf.DateTime,  \r\n vPerf.AverageValue,  \r\n vPerf.MinValue,  \r\n vPerf.MaxValue,  \r\n vPerformanceRuleInstance.InstanceName,   \r\n vManagedEntity.Path,   \r\n vPerformanceRule.ObjectName,   \r\n  vPerformanceRule.CounterName  \r\n FROM OperationsManagerDW.Perf.vPerfHourly AS vPerf INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRuleInstance ON OperationsManagerDW.dbo.vPerformanceRuleInstance.PerformanceRuleInstanceRowId = vPerf.PerformanceRuleInstanceRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vManagedEntity ON vPerf.ManagedEntityRowId = OperationsManagerDW.dbo.vManagedEntity.ManagedEntityRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRule ON OperationsManagerDW.dbo.vPerformanceRuleInstance.RuleRowId = OperationsManagerDW.dbo.vPerformanceRule.RuleRowId   \r\n WHERE   \r\n (OperationsManagerDW.dbo.vPerformanceRule.ObjectName like '%disk%')  \r\n --AND OperationsManagerDW.dbo.vPerformanceRule.CounterName like '%sec/T%'  \r\n AND vManagedEntity.Path like '%-DC02%'  \r\n and vPerf.DateTime > getdate()-30\r\n Order by [DateTime] desc"
    }
   ]
  },
  {
   "title": "Top 20 Alerts in an Operational Database, by Repeat Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT TOP 20 SUM(RepeatCount+1) AS RepeatCount, AlertStringName, AlertStringDescription, Name   \r\n FROM Alertview WITH (NOLOCK)   \r\n WHERE Timeraised is not NULL   \r\n GROUP BY AlertStringName, AlertStringDescription, MonitoringRuleId, Name   \r\n ORDER BY RepeatCount DESC"
    }
   ]
  },
  {
   "title": "Most Common Events by event number",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": " SELECT top 50 EventDisplayNumber, COUNT(*) AS TotalEvents   \r\n FROM OperationsManagerDW.Event.vEvent   \r\n GROUP BY EventDisplayNumber   \r\n ORDER BY TotalEvents DESC"
    }
   ]
  },
  {
   "title": "Health Service Down",
   "type": "table",
   "description": "'No data to show' is good! It means there are no unresponsive servers!",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": " SELECT bme.DisplayName,s.LastModified as LastModifiedUTC, dateadd(hh,-5,s.LastModified) as 'LastModifiedCST (GMT-5)'   \r\n FROM state AS s, BaseManagedEntity AS bme   \r\n WHERE s.basemanagedentityid = bme.basemanagedentityid   \r\n AND s.monitorid   \r\n IN (SELECT MonitorId FROM Monitor WHERE MonitorName = 'Microsoft.SystemCenter.HealthService.ComputerDown')   \r\n AND s.Healthstate = '3' AND bme.IsDeleted = '0'   \r\n ORDER BY s.Lastmodified DESC  "
    }
   ]
  },
  {
   "title": "Top 20 Alerts in an Operational Database, by Alert Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": " SELECT TOP 20 SUM(1) AS AlertCount, AlertStringName, AlertStringDescription, Name   \r\n FROM Alertview WITH (NOLOCK)   \r\n WHERE TimeRaised is not NULL   \r\n GROUP BY AlertStringName, AlertStringDescription, MonitoringRuleId, Name   \r\n ORDER BY AlertCount DESC  "
    }
   ]
  },
  {
   "title": "Rules per MP by category",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": " SELECT mp.MPName, r.RuleCategory, COUNT(*) As RulesPerMPPerCategory   \r\n FROM Rules r   \r\n INNER JOIN ManagementPack mp ON mp.ManagementPackID = r.ManagementPackID   \r\n GROUP BY mp.MPName, r.RuleCategory   \r\n ORDER BY RulesPerMPPerCategory DESC"
    }
   ]
  },
  {
   "title": "% Free Space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": " SELECT   \r\n vPerf.DateTime as time,\r\n vPerformanceRuleInstance.InstanceName,\r\n vPerf.AverageValue\r\n FROM OperationsManagerDW.Perf.vPerfHourly AS vPerf INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRuleInstance ON OperationsManagerDW.dbo.vPerformanceRuleInstance.PerformanceRuleInstanceRowId = vPerf.PerformanceRuleInstanceRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vManagedEntity ON vPerf.ManagedEntityRowId = OperationsManagerDW.dbo.vManagedEntity.ManagedEntityRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRule ON OperationsManagerDW.dbo.vPerformanceRuleInstance.RuleRowId = OperationsManagerDW.dbo.vPerformanceRule.RuleRowId   \r\n WHERE   \r\n (OperationsManagerDW.dbo.vPerformanceRule.ObjectName like '%disk%')  \r\n AND OperationsManagerDW.dbo.vPerformanceRule.CounterName like '% Free Space'  \r\n AND vManagedEntity.Path like '%SCOM%'\r\n and vPerf.DateTime > getdate()-30\r\n Order by datetime"
    }
   ]
  },
  {
   "title": "Noisiest monitors changing state in the database in the last 7 days.",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select distinct top 50 count(sce.StateId) as NumStateChanges,   \r\n m.DisplayName as MonitorDisplayName,   \r\n m.Name as MonitorIdName,   \r\n mt.typename AS TargetClass   \r\n from StateChangeEvent sce with (nolock)   \r\n join state s with (nolock) on sce.StateId = s.StateId   \r\n join monitorview m with (nolock) on s.MonitorId = m.Id   \r\n join managedtype mt with (nolock) on m.TargetMonitoringClassId = mt.ManagedTypeId   \r\n where m.IsUnitMonitor = 1   \r\n  -- Scoped to within last 7 days   \r\n AND sce.TimeGenerated > dateadd(dd,-7,getutcdate())   \r\n group by m.DisplayName, m.Name,mt.typename   \r\n order by NumStateChanges desc"
    }
   ]
  }
 ]
}