{
 "title": "System Center Operations Manager - Server Performance",
 "description": "Monitored Server Performance",
 "tags": [
  "SCOM",
  "MSSQL"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Server",
    "query": "Select Path FROM [OperationsManagerDW].[dbo].[vManagedEntity]   where Path is not null    and FullName like '%OperatingSystem%'"
   },
   {
    "name": "MonitoredServer",
    "query": "SELECT [Path]\n  FROM [OperationsManager].[dbo].[BaseManagedEntity]\n  where [FullName] like 'Microsoft.SystemCenter.HealthService%' and [Path] not like 'Microsoft%'\n  order by [Path]"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Up Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": " SELECT top 1\r\n  \r\n  vPerf.MaxValue\r\n FROM OperationsManagerDW.Perf.vPerfHourly AS vPerf INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRuleInstance ON OperationsManagerDW.dbo.vPerformanceRuleInstance.PerformanceRuleInstanceRowId = vPerf.PerformanceRuleInstanceRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vManagedEntity ON vPerf.ManagedEntityRowId = OperationsManagerDW.dbo.vManagedEntity.ManagedEntityRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRule ON OperationsManagerDW.dbo.vPerformanceRuleInstance.RuleRowId = OperationsManagerDW.dbo.vPerformanceRule.RuleRowId   \r\n WHERE   \r\n OperationsManagerDW.dbo.vPerformanceRule.CounterName like 'System Up Time'  \r\n AND vManagedEntity.Path like '[[Server]]'\r\n Order by datetime desc"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": " SELECT top 1\r\nvPerf.MaxValue as value\r\n FROM OperationsManagerDW.Perf.vPerfHourly AS vPerf INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRuleInstance ON OperationsManagerDW.dbo.vPerformanceRuleInstance.PerformanceRuleInstanceRowId = vPerf.PerformanceRuleInstanceRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vManagedEntity ON vPerf.ManagedEntityRowId = OperationsManagerDW.dbo.vManagedEntity.ManagedEntityRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRule ON OperationsManagerDW.dbo.vPerformanceRuleInstance.RuleRowId = OperationsManagerDW.dbo.vPerformanceRule.RuleRowId   \r\n WHERE   \r\n (OperationsManagerDW.dbo.vPerformanceRule.ObjectName like 'Memory')  \r\n AND OperationsManagerDW.dbo.vPerformanceRule.CounterName like 'PercentMemoryUsed'  \r\n AND vManagedEntity.Path like '[[Server]]'\r\norder by vPerf.Datetime desc"
    }
   ]
  },
  {
   "title": "Processor Time",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": " SELECT top 1\r\nvPerf.MaxValue as value\r\n FROM OperationsManagerDW.Perf.vPerfHourly AS vPerf INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRuleInstance ON OperationsManagerDW.dbo.vPerformanceRuleInstance.PerformanceRuleInstanceRowId = vPerf.PerformanceRuleInstanceRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vManagedEntity ON vPerf.ManagedEntityRowId = OperationsManagerDW.dbo.vManagedEntity.ManagedEntityRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRule ON OperationsManagerDW.dbo.vPerformanceRuleInstance.RuleRowId = OperationsManagerDW.dbo.vPerformanceRule.RuleRowId   \r\n WHERE   \r\n OperationsManagerDW.dbo.vPerformanceRule.CounterName like '% Processor Time'  \r\n AND vManagedEntity.Path like '[[Server]]'\r\norder by vPerf.Datetime desc"
    }
   ]
  },
  {
   "title": "Bandwidth Used Total",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": " SELECT top 1\r\nvPerf.MaxValue as value\r\n FROM OperationsManagerDW.Perf.vPerfHourly AS vPerf INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRuleInstance ON OperationsManagerDW.dbo.vPerformanceRuleInstance.PerformanceRuleInstanceRowId = vPerf.PerformanceRuleInstanceRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vManagedEntity ON vPerf.ManagedEntityRowId = OperationsManagerDW.dbo.vManagedEntity.ManagedEntityRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRule ON OperationsManagerDW.dbo.vPerformanceRuleInstance.RuleRowId = OperationsManagerDW.dbo.vPerformanceRule.RuleRowId   \r\n WHERE   \r\n OperationsManagerDW.dbo.vPerformanceRule.CounterName like 'PercentBandwidthUsedTotal'  \r\n AND vManagedEntity.Path like '[[Server]]'\r\norder by vPerf.Datetime desc"
    }
   ]
  },
  {
   "title": "System Disk % Free Space",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": " SELECT top 1\r\nvPerf.MaxValue as value\r\n FROM OperationsManagerDW.Perf.vPerfHourly AS vPerf INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRuleInstance ON OperationsManagerDW.dbo.vPerformanceRuleInstance.PerformanceRuleInstanceRowId = vPerf.PerformanceRuleInstanceRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vManagedEntity ON vPerf.ManagedEntityRowId = OperationsManagerDW.dbo.vManagedEntity.ManagedEntityRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRule ON OperationsManagerDW.dbo.vPerformanceRuleInstance.RuleRowId = OperationsManagerDW.dbo.vPerformanceRule.RuleRowId   \r\n WHERE   \r\n OperationsManagerDW.dbo.vPerformanceRule.CounterName like '% Free Space'\r\n AND vPerformanceRuleInstance.InstanceName like 'C:'\r\n AND vManagedEntity.Path like '[[Server]]'\r\norder by vPerf.Datetime desc"
    }
   ]
  },
  {
   "title": "$Server Performance Counter Query",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": " SELECT   \r\n vPerf.DateTime,  \r\n vPerf.SampleCount,   \r\n vPerf.AverageValue,  \r\n vPerf.MinValue,  \r\n vPerf.MaxValue,  \r\n vPerf.StandardDeviation,   \r\n vPerformanceRuleInstance.InstanceName,   \r\n vManagedEntity.Path,   \r\n vPerformanceRule.ObjectName,   \r\n  vPerformanceRule.CounterName  \r\n FROM OperationsManagerDW.Perf.vPerfHourly AS vPerf INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRuleInstance ON OperationsManagerDW.dbo.vPerformanceRuleInstance.PerformanceRuleInstanceRowId = vPerf.PerformanceRuleInstanceRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vManagedEntity ON vPerf.ManagedEntityRowId = OperationsManagerDW.dbo.vManagedEntity.ManagedEntityRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRule ON OperationsManagerDW.dbo.vPerformanceRuleInstance.RuleRowId = OperationsManagerDW.dbo.vPerformanceRule.RuleRowId   \r\n WHERE   \r\n vManagedEntity.Path like '[[Server]]'  \r\n and vPerf.DateTime > getdate()\r\n order by [DateTime] desc"
    }
   ]
  },
  {
   "title": "$Server Newest 20 Alerts",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT TOP 20 \r\n  TimeRaised\r\n  ,AlertStringName\r\n  ,TicketId\r\n  \r\n  ,Category\r\n  ,Owner\r\n  ,CustomField1 as [Ticket Status]\r\n  ,CustomField5 as [Assigned Group]\r\n  ,CustomField6 as [Impact]\r\n  ,CustomField6 as [Urgency]\r\nFROM Alertview WITH (NOLOCK) \r\nWHERE Timeraised is not NULL and ResolutionState < 256 and (MonitoringObjectName like '%[[Server]]%' or MonitoringObjectPath like '%[[Server]]%')\r\nORDER BY [TimeRaised] desc"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "$Server Processor Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": " SELECT   \r\n vPerf.DateTime as time,\r\n vPerformanceRule.ObjectName as label,\r\n  vPerf.MaxValue\r\n FROM OperationsManagerDW.Perf.vPerfHourly AS vPerf INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRuleInstance ON OperationsManagerDW.dbo.vPerformanceRuleInstance.PerformanceRuleInstanceRowId = vPerf.PerformanceRuleInstanceRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vManagedEntity ON vPerf.ManagedEntityRowId = OperationsManagerDW.dbo.vManagedEntity.ManagedEntityRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRule ON OperationsManagerDW.dbo.vPerformanceRuleInstance.RuleRowId = OperationsManagerDW.dbo.vPerformanceRule.RuleRowId   \r\n WHERE   \r\n OperationsManagerDW.dbo.vPerformanceRule.CounterName like 'Processor Queue Length'  \r\n AND vManagedEntity.Path like '[[Server]]'\r\n and $__timeFilter(vPerf.Datetime)\r\n Order by datetime"
    }
   ]
  },
  {
   "title": "$Server % Processor Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": " SELECT   \r\n vPerf.DateTime as time,\r\n vPerformanceRule.ObjectName as label,\r\n  vPerf.MaxValue\r\n FROM OperationsManagerDW.Perf.vPerfHourly AS vPerf INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRuleInstance ON OperationsManagerDW.dbo.vPerformanceRuleInstance.PerformanceRuleInstanceRowId = vPerf.PerformanceRuleInstanceRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vManagedEntity ON vPerf.ManagedEntityRowId = OperationsManagerDW.dbo.vManagedEntity.ManagedEntityRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRule ON OperationsManagerDW.dbo.vPerformanceRuleInstance.RuleRowId = OperationsManagerDW.dbo.vPerformanceRule.RuleRowId   \r\n WHERE   \r\n OperationsManagerDW.dbo.vPerformanceRule.CounterName like '% Processor Time'  \r\n AND vManagedEntity.Path like '[[Server]]'\r\n and $__timeFilter(vPerf.Datetime)\r\n Order by datetime"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "$Server % Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": " SELECT   \r\n vPerf.DateTime as time,\r\n vPerformanceRuleInstance.InstanceName as [NIC],\r\n vPerf.MaxValue as [Used %]\r\n FROM OperationsManagerDW.Perf.vPerfHourly AS vPerf INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRuleInstance ON OperationsManagerDW.dbo.vPerformanceRuleInstance.PerformanceRuleInstanceRowId = vPerf.PerformanceRuleInstanceRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vManagedEntity ON vPerf.ManagedEntityRowId = OperationsManagerDW.dbo.vManagedEntity.ManagedEntityRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRule ON OperationsManagerDW.dbo.vPerformanceRuleInstance.RuleRowId = OperationsManagerDW.dbo.vPerformanceRule.RuleRowId   \r\n WHERE   \r\n (OperationsManagerDW.dbo.vPerformanceRule.ObjectName like 'Memory')  \r\n AND OperationsManagerDW.dbo.vPerformanceRule.CounterName like 'PercentMemoryUsed'  \r\n AND vManagedEntity.Path like '[[Server]]'\r\n and $__timeFilter(vPerf.Datetime)\r\norder by vPerf.Datetime"
    }
   ]
  },
  {
   "title": "$Server Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": " SELECT   \r\n vPerf.DateTime as time,\r\n OperationsManagerDW.dbo.vPerformanceRule.CounterName as [Counter],\r\n vPerf.MaxValue\r\n FROM OperationsManagerDW.Perf.vPerfHourly AS vPerf INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRuleInstance ON OperationsManagerDW.dbo.vPerformanceRuleInstance.PerformanceRuleInstanceRowId = vPerf.PerformanceRuleInstanceRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vManagedEntity ON vPerf.ManagedEntityRowId = OperationsManagerDW.dbo.vManagedEntity.ManagedEntityRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRule ON OperationsManagerDW.dbo.vPerformanceRuleInstance.RuleRowId = OperationsManagerDW.dbo.vPerformanceRule.RuleRowId   \r\n WHERE   \r\n (OperationsManagerDW.dbo.vPerformanceRule.ObjectName like 'Memory')  \r\n AND OperationsManagerDW.dbo.vPerformanceRule.CounterName like '%Bytes'  \r\n AND vManagedEntity.Path like '[[Server]]'\r\n and $__timeFilter(vPerf.Datetime)\r\norder by vPerf.Datetime"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "$Server Network: Bytes per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": " SELECT   \r\n vPerf.DateTime as time,\r\n vPerformanceRuleInstance.InstanceName as [NIC],\r\n vPerf.MaxValue as value\r\n FROM OperationsManagerDW.Perf.vPerfHourly AS vPerf INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRuleInstance ON OperationsManagerDW.dbo.vPerformanceRuleInstance.PerformanceRuleInstanceRowId = vPerf.PerformanceRuleInstanceRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vManagedEntity ON vPerf.ManagedEntityRowId = OperationsManagerDW.dbo.vManagedEntity.ManagedEntityRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRule ON OperationsManagerDW.dbo.vPerformanceRuleInstance.RuleRowId = OperationsManagerDW.dbo.vPerformanceRule.RuleRowId   \r\n WHERE   \r\n (OperationsManagerDW.dbo.vPerformanceRule.ObjectName like 'Network%')  \r\n AND OperationsManagerDW.dbo.vPerformanceRule.CounterName like 'Bytes Total/sec'  \r\n AND vManagedEntity.Path like '[[Server]]'\r\n and $__timeFilter(vPerf.Datetime)\r\norder by vPerf.Datetime"
    }
   ]
  },
  {
   "title": "$Server % Bandwidth Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": " SELECT   \r\n vPerf.DateTime as time,\r\n vPerformanceRuleInstance.InstanceName as [NIC],\r\n vPerf.MaxValue as value\r\n FROM OperationsManagerDW.Perf.vPerfHourly AS vPerf INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRuleInstance ON OperationsManagerDW.dbo.vPerformanceRuleInstance.PerformanceRuleInstanceRowId = vPerf.PerformanceRuleInstanceRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vManagedEntity ON vPerf.ManagedEntityRowId = OperationsManagerDW.dbo.vManagedEntity.ManagedEntityRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRule ON OperationsManagerDW.dbo.vPerformanceRuleInstance.RuleRowId = OperationsManagerDW.dbo.vPerformanceRule.RuleRowId   \r\n WHERE   \r\n (OperationsManagerDW.dbo.vPerformanceRule.ObjectName like 'Network Adapter')  \r\n AND OperationsManagerDW.dbo.vPerformanceRule.CounterName like 'PercentBandwidthUsedTotal'  \r\n AND vManagedEntity.Path like '[[Server]]'\r\n and $__timeFilter(vPerf.Datetime)\r\norder by vPerf.Datetime"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "$Server Free Megabytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": " SELECT   \r\n vPerf.DateTime as time,\r\n vPerformanceRuleInstance.InstanceName as [Drive Letter],\r\n vPerf.MaxValue as value\r\n FROM OperationsManagerDW.Perf.vPerfHourly AS vPerf \r\n INNER JOIN OperationsManagerDW.dbo.vPerformanceRuleInstance ON OperationsManagerDW.dbo.vPerformanceRuleInstance.PerformanceRuleInstanceRowId = vPerf.PerformanceRuleInstanceRowId \r\n INNER JOIN OperationsManagerDW.dbo.vManagedEntity ON vPerf.ManagedEntityRowId = OperationsManagerDW.dbo.vManagedEntity.ManagedEntityRowId \r\n INNER JOIN OperationsManagerDW.dbo.vPerformanceRule ON OperationsManagerDW.dbo.vPerformanceRuleInstance.RuleRowId = OperationsManagerDW.dbo.vPerformanceRule.RuleRowId   \r\n WHERE   \r\n (OperationsManagerDW.dbo.vPerformanceRule.ObjectName like '%disk%')  \r\n AND OperationsManagerDW.dbo.vPerformanceRule.CounterName like 'Free Megabytes'  \r\n AND vManagedEntity.Path like '[[Server]]'\r\n and $__timeFilter(vPerf.Datetime)\r\norder by vPerf.Datetime"
    }
   ]
  },
  {
   "title": "$Server % Idle Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": " SELECT   \r\n vPerf.DateTime as time,\r\n vPerformanceRuleInstance.InstanceName as label,\r\n  vPerf.MaxValue\r\n FROM OperationsManagerDW.Perf.vPerfHourly AS vPerf INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRuleInstance ON OperationsManagerDW.dbo.vPerformanceRuleInstance.PerformanceRuleInstanceRowId = vPerf.PerformanceRuleInstanceRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vManagedEntity ON vPerf.ManagedEntityRowId = OperationsManagerDW.dbo.vManagedEntity.ManagedEntityRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRule ON OperationsManagerDW.dbo.vPerformanceRuleInstance.RuleRowId = OperationsManagerDW.dbo.vPerformanceRule.RuleRowId   \r\n WHERE   \r\n (OperationsManagerDW.dbo.vPerformanceRule.ObjectName like '%disk%')  \r\n AND OperationsManagerDW.dbo.vPerformanceRule.CounterName like '% Idle Time'  \r\n AND vManagedEntity.Path like '[[Server]]'\r\n and $__timeFilter(vPerf.Datetime)\r\n Order by datetime"
    }
   ]
  },
  {
   "title": "$Server Avg. Disk sec/Transfer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": " SELECT   \r\n vPerf.DateTime as time,\r\n vPerformanceRuleInstance.InstanceName as [Drive Letter],\r\n vPerf.MaxValue as value\r\n FROM OperationsManagerDW.Perf.vPerfHourly AS vPerf INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRuleInstance ON OperationsManagerDW.dbo.vPerformanceRuleInstance.PerformanceRuleInstanceRowId = vPerf.PerformanceRuleInstanceRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vManagedEntity ON vPerf.ManagedEntityRowId = OperationsManagerDW.dbo.vManagedEntity.ManagedEntityRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRule ON OperationsManagerDW.dbo.vPerformanceRuleInstance.RuleRowId = OperationsManagerDW.dbo.vPerformanceRule.RuleRowId   \r\n WHERE   \r\n (OperationsManagerDW.dbo.vPerformanceRule.ObjectName like '%disk%')  \r\n AND OperationsManagerDW.dbo.vPerformanceRule.CounterName like 'Avg. Disk sec/Transfer'  \r\n AND vManagedEntity.Path like '[[Server]]'\r\n and $__timeFilter(vPerf.Datetime)\r\norder by vPerf.Datetime"
    }
   ]
  },
  {
   "title": "$Server Current Disk Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": " SELECT   \r\n vPerf.DateTime as time,\r\n vPerformanceRuleInstance.InstanceName as [Drive Letter],\r\n vPerf.MaxValue as value\r\n FROM OperationsManagerDW.Perf.vPerfHourly AS vPerf INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRuleInstance ON OperationsManagerDW.dbo.vPerformanceRuleInstance.PerformanceRuleInstanceRowId = vPerf.PerformanceRuleInstanceRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vManagedEntity ON vPerf.ManagedEntityRowId = OperationsManagerDW.dbo.vManagedEntity.ManagedEntityRowId INNER JOIN  \r\n  OperationsManagerDW.dbo.vPerformanceRule ON OperationsManagerDW.dbo.vPerformanceRuleInstance.RuleRowId = OperationsManagerDW.dbo.vPerformanceRule.RuleRowId   \r\n WHERE   \r\n (OperationsManagerDW.dbo.vPerformanceRule.ObjectName like '%disk%')  \r\n AND OperationsManagerDW.dbo.vPerformanceRule.CounterName like 'Current Disk Queue Length'  \r\n AND vManagedEntity.Path like '[[Server]]'\r\n and $__timeFilter(vPerf.Datetime)\r\norder by vPerf.Datetime"
    }
   ]
  },
  {
   "title": "Health State - All Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "[[MonitoredServer]]",
     "type": "stat",
     "description": "Up/Down state of servers monitored by SCOM",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 64 },
     "repeat": "MonitoredServer",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT [HealthState]\r\n  FROM [OperationsManager].[dbo].[StateView] as SV\r\n  inner join [OperationsManager].[dbo].[BaseManagedEntity] as Entity on Entity.BaseManagedEntityId = SV.[BaseManagedEntityId]\r\n  where [MonitorName] = 'Microsoft.Windows.Server.Computer.OSAvailabilityRollup' and Entity.[DisplayName] = [[MonitoredServer]]"
      }
     ]
    }
   ]
  }
 ]
}